/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-05-06 10:57:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- 설명용\r\n");
      out.write("		web.xml을 생성안하면 어떻게 되는가?\r\n");
      out.write("		프로젝트에 웰컴페이지에 대한 요소 정보가 없지만\r\n");
      out.write("		서버에 웰컴페이지에 대한 요소가 있다.\r\n");
      out.write("		즉, 특별한 설정이 없다면 기본적으로 index.html/jsp 등을 사용하면 된다.\r\n");
      out.write("	 -->\r\n");
      out.write("	<h1>웰컴파일입니다.</h1>\r\n");
      out.write("\r\n");
      out.write("	<h2> *EL (Expression Language)</h2>\r\n");
      out.write("	\r\n");
      out.write("	<h3> EL구문 학습 </h3>\r\n");
      out.write("	\r\n");
      out.write("	<a href=\"http://localhost:8088/action/el.do\">서블릿으로 요청~~</a> <!-- 서블릿 매핑값 // 어떤 서블릿을 호출할 것인가-->\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<pre>\r\n");
      out.write("		JSP상 자바에서 만들어진 값을 출력하고 싶다면 => &lt;%=변수 %>\r\n");
      out.write("		EL구문을 사용하면 ${변수} 형식으로 작성할 수 있음 \r\n");
      out.write("	</pre>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	");

		String str ="편리한데 불편함";
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.print(str );
      out.write(" <br>\r\n");
      out.write("	ㅇㅇ?\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${str}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	sessionScope : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ academy }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <br>\r\n");
      out.write("	requestScope : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ classRoom }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <br>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- \r\n");
      out.write("		JSP를 이루는 구성요소\r\n");
      out.write("		\r\n");
      out.write("		1. Scripting Element : JSP상에서 자바코드를 직접 기술할 수 있게 해주는 요소\r\n");
      out.write("		\r\n");
      out.write("		2. 문자열 : HTML, CSS, J.S\r\n");
      out.write("		\r\n");
      out.write("		3. 지시어 : JSP페이지 정보를 기술한다거나 (page), 포함시킬 때 사용(include) : 지시어 앞에는 @가 붙음\r\n");
      out.write("		\r\n");
      out.write("		4. JSP Action Tag : XML기술을 사용해서 기존의 JSP문법을 확장하는 용도의 태그들\r\n");
      out.write("		\r\n");
      out.write("	 -->\r\n");
      out.write("	\r\n");
      out.write("	<h2>*JSP Action Tag</h2>\r\n");
      out.write("	\r\n");
      out.write("	<h3>1. 표준 액션 태그</h3>\r\n");
      out.write("	<a href=\"http://localhost:8088/action/include.do\">흐으음</a>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<a href=\"http://localhost:8088/action/forward.do\">더 좋은 액션태그</a>\r\n");
      out.write("	\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("	<h3> 2. 커스텀 액션 태그 </h3>\r\n");
      out.write("	\r\n");
      out.write("	<a href=\"/action/jstl.do\">JSTL</a>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<h3> 3. 개인 연습 forward </h3>\r\n");
      out.write("	<a href=\"/action/test.do\">asdf</a>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("		const v = '알쏭달쏭';\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		// 스크립트의 $앞에 \\를 붙혀야 정상작동함\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
